Repository gipo999/smispi, pull requests merged in 2024-05, with the labels that each got.

#27 26 gh build check actions and dep submission / review
  .commitlintrc.js
  .github/inactive/gradle.yml
  .github/workflows/dependency-review.yml
  .github/workflows/dependency-submission-download-submit.yml
  .github/workflows/dependency-submission-on-pr.yml
  .github/workflows/dependency-submission.yml
  .github/workflows/gradle-check-build.yml
Labels: bug

#38 Fix dep vulnerability check action
  .github/inactive/dependency-review-on-push.yml
  .github/workflows/dependency-review-on-pr.yml
  .github/workflows/gradle-check-build.yml
Labels: root, Actions

#43 Refactor semgrep action, add to docs
  .github/workflows/semgrep.yml
Labels: Actions

#46 32 pit mutations and publish to gh pages. Remove main from CI for now
  .github/workflows/gradle-check-build.yml
  .github/workflows/semgrep.yml
  build.gradle
  settings.gradle
Labels: enhancement, root, Actions, Gradle

#50 Publishing docs
  README.md
  build.gradle
  docs/publishing/intro.md
  docs/semantic-release/intro.md
Labels: documentation, root, Gradle

#51 Tentative publishing on github package registry
  .github/workflows/github_publish.yml
  build.gradle
  docs/publishing/alternatives_to_maven_central.md
  docs/publishing/creating_a_release.md
  docs/publishing/how_to_publish.md
  docs/publishing/maven_central.md
  package.json
Labels: documentation, root, Actions, Gradle

#52 ci: testing different publish strat
  .github/workflows/github_publish.yml
  build.gradle
Labels: root, Actions, Gradle

#55 fix: tentative fix for gh publish
  .github/workflows/github_publish.yml
Labels: Actions

#59 fix: tentative fix ffor semantic release not working for dev and pre-…
  package.json
  release.config.js
Labels: root

#61 fix: handle name cut correctly for dev and pre-release
  .github/workflows/github_publish.yml
Labels: Actions

#63 First main release
  .github/labeler.yml
  .github/workflows/github_publish.yml
  package.json
  release.config.js
Labels: root, Actions, release

#64 fix: fix comapitbility for windows unix gradlew executable for ci
  .pre-commit-config.yaml
  package.json
  scripts/README.md
  scripts/gradlew.cjs
Labels: root, issue

#66 Cleanup, openrewrite. pre checkstyle
  .commitlintrc.js
  .github/dependabot.yml
  .github/inactive/mirror-repo.yml
  .github/workflows/gh-pages.yml
  .github/workflows/github-publish.yml
  .idea/google-java-format.xml
  .pre-commit-config.yaml
  build.gradle
  config/checkstyle/checkstyle.xml
  docs/gh-pages/index.html
  docs/semantic-release/intro.md
  package-lock.json
  package.json
  release.config.js
  scripts/gradlew.cjs
  settings.gradle
  src/main/java/net/syn3rgy/core/spi/DefaultImplementationSelector.java
  src/main/java/net/syn3rgy/core/spi/Implementation.java
  src/main/java/net/syn3rgy/core/spi/ImplementationParams.java
  src/main/java/net/syn3rgy/core/spi/ImplementationSelector.java
  src/main/java/net/syn3rgy/core/spi/Implementations.java
  src/main/java/net/syn3rgy/core/spi/ImplementationsFilter.java
  src/main/java/net/syn3rgy/core/spi/NamedService.java
  src/main/java/net/syn3rgy/core/spi/PrioritizedService.java
  src/main/java/net/syn3rgy/core/spi/Spi.java
  src/test/java/net/syn3rgy/core/spi/params/StdCustParams.java
  src/test/java/net/syn3rgy/core/spi/selectors/CustomSelector.java
Labels: documentation, root, Actions, Gradle, source, tests

#72 fix: move pitest and javadoc to new directories
  .github/workflows/gh-pages.yml
Labels: Actions, issue

#73 Refactor remove useless checks
  .github/inactive/gradle.yml
  .github/workflows/gradle-check-build.yml
  docs/gh-pages/index.html
Labels: documentation, Actions

#82 docs: enhance documentation in readme
  README.md
  docs/assets/flow.svg
  docs/assets/peek_pre-commit.gif
  docs/assets/peek_push.gif
Labels: documentation, root

#89 refactor: remove gradle dupes
  build.gradle
Labels: root, Gradle

#90 feat: improve node scripts for compatibility
  README.md
  package.json
  scripts/execCmd.cjs
  scripts/gradlew.cjs
  scripts/install-hooks.cjs
Labels: root

#91 docs: add scoop install python comment
  README.md
Labels: root

#94 fix: remove bad commit
  src/main/java/net/syn3rgy/core/spi/Spi.java
Labels: source

#97 fix: fix zip command for asset release
  .github/workflows/releaser.yml
Labels: Actions, issue

#98 fix: was using build task instead of javadoc
  .github/workflows/releaser.yml
Labels: Actions, issue

#100 feat: disable gh actions on draft prs
  .github/workflows/dependency-review-on-pr.yml
  .github/workflows/dependency-submission-download-submit.yml
  .github/workflows/dependency-submission-on-pr.yml
  .github/workflows/dependency-submission-on-push.yml
  .github/workflows/gh-pages.yml
  .github/workflows/github-publish.yml
  .github/workflows/gradle-check-build.yml
  .github/workflows/greetings.yml
  .github/workflows/releaser.yml
  .github/workflows/semgrep.yml
  .github/workflows/stale.yml
Labels: Actions

#108 Maven publish
  .github/workflows/gradle-check-build.yml
  .github/workflows/semgrep.yml
  .github/workflows/snyk.yml
  README.md
  release.config.js
Labels: root, Actions

#110 fix: fix broken publish action
  .github/workflows/publish.yml
  build.gradle
  release.config.js
Labels: root, Actions, Gradle

#113 Maven publish
  .github/workflows/publish.yml
  .github/workflows/snyk.yml
  LICENSE.md
  build.gradle
  docs/publishing/signig_packages.md
Labels: documentation, root, Actions, Gradle

#114 Update publish.yml
  .github/workflows/publish.yml
Labels: Actions

#115 fix: add comment on maven
  build.gradle
Labels: root, Gradle

#116 Maven publish
  .github/workflows/publish.yml
  README.md
  build.gradle
Labels: root, Actions, Gradle

#117 Maven publish
  .github/workflows/publish.yml
  build.gradle
Labels: root, Actions, Gradle

#119 118 clean
  .commitlintrc.js
  .github/actions/ci-setup/action.yml
  .github/labeler.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review-on-pr.yml
  .github/workflows/dependency-submission-download-submit.yml
  .github/workflows/dependency-submission-on-pr.yml
  .github/workflows/dependency-submission-on-push.yml
  .github/workflows/gh-pages.yml
  .github/workflows/gradle-check-build.yml
  .github/workflows/greetings.yml
  .github/workflows/publish.yml
  .github/workflows/releaser.yml
  .github/workflows/semgrep.yml
  .github/workflows/snyk.yml
  .pre-commit-config.yaml
  build.gradle
  release.config.js
  scripts/README.md
  settings.gradle
Labels: root, Actions, Gradle, issue

#122 docs: update requiremenets
  README.md
Labels: root

#123 refactor: remove pull_request trigger from semgrep and snyk workflows
  .github/workflows/semgrep.yml
  .github/workflows/snyk.yml
Labels: Actions
